platform :ios, '9.0'
inhibit_all_warnings!

target 'AppBOA' do
    use_frameworks!

    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'MBProgressHUD'
    pod 'ObjectMapper+Realm'
    pod 'ObjectMapperAdditions/Realm'
    pod 'ReachabilitySwift', '~> 4.1.0'
    
end
